import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Context from '@/contexts/context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cebu City Attendance',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Context>{children}</Context>
      </body>
    </html>
  );
}
