import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cebu City Attendance',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='w-screen h-1/4 min-h-min flex relative m-5'>
          <Image
            priority
            src='/images/Ph_seal_cebucity.png'
            fill={true}
            objectFit='contain'
            alt=''
          />
        </header>
        <main className='w-screen px-10 h-3/4 flex justify-center'>{children}</main>
      </body>
    </html>
  );
}
